#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom -f --daemon --config $HOME/.config/picom/picom.conf &
pgrep -x feh > /dev/null || feh --bg-fill $HOME/.backgrounds/bocchi03.png &
$HOME/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Code desktop='^3' follow=on
